import {
  ACCESSORY_SIZE,
  ACTIVE_LABEL_FONT_SIZE,
  TEXT_FIELD_ACCESSORY_MARGIN_HORIZONTAL,
  TEXT_FIELD_INPUT_WRAPPER_PADDING_HORIZONTAL,
  TEXT_FIELD_PADDING_VERTICAL,
} from '../constants';

// ==================
// LABEL POSITIONING
// ==================

export const LABEL_LEFT_OFFSET_WITH_ACCESSORY =
  ACCESSORY_SIZE +
  TEXT_FIELD_ACCESSORY_MARGIN_HORIZONTAL +
  TEXT_FIELD_INPUT_WRAPPER_PADDING_HORIZONTAL;

export const LABEL_LEFT_OFFSET_WITHOUT_ACCESSORY =
  TEXT_FIELD_INPUT_WRAPPER_PADDING_HORIZONTAL;

export const ACTIVE_LABEL_TOP_POSITION = TEXT_FIELD_PADDING_VERTICAL;

// ==================
// PLACEHOLDER & MULTILINE POSITIONING
// ==================

export const PADDING_TOP = ACTIVE_LABEL_FONT_SIZE + TEXT_FIELD_PADDING_VERTICAL;

// ==================
// OPACITY
// ==================

export const FILLED_CONTAINER_ALPHA = 0.04;
