import {
  ACCESSORY_SIZE,
  ACTIVE_LABEL_FONT_SIZE,
  TEXT_FIELD_ACCESSORY_MARGIN_HORIZONTAL,
  TEXT_FIELD_INPUT_WRAPPER_PADDING_HORIZONTAL,
  TEXT_FIELD_PADDING_VERTICAL,
} from '../constants';

// ==================
// LABEL POSITIONING
// ==================

export const LABEL_START_OFFSET_WITH_ACCESSORY =
  ACCESSORY_SIZE +
  TEXT_FIELD_ACCESSORY_MARGIN_HORIZONTAL +
  TEXT_FIELD_INPUT_WRAPPER_PADDING_HORIZONTAL;

export const LABEL_START_OFFSET_WITHOUT_ACCESSORY =
  TEXT_FIELD_INPUT_WRAPPER_PADDING_HORIZONTAL;

export const ACTIVE_LABEL_TOP_POSITION = TEXT_FIELD_PADDING_VERTICAL;

// ==================
// MULTILINE POSITIONING
// ==================

export const MULTILINE_PADDING_TOP =
  ACTIVE_LABEL_FONT_SIZE + TEXT_FIELD_PADDING_VERTICAL;

// ==================
// OPACITY
// ==================

export const DISABLED_CONTAINER_OPACITY = 0.04;
