import callstack from '@callstack/eslint-config/react-native.flat.js';
import { defineConfig } from 'eslint/config';
import testingLibrary from 'eslint-plugin-testing-library';
import tseslint from 'typescript-eslint';

const testingLibraryReact = testingLibrary.configs['flat/react'];

export default defineConfig(
  {
    ignores: [
      // jest
      'coverage/',
      'cache/jest/',
      'jest/testSetup.js',
      '**/__fixtures__/',
      '__ts-tests__/',

      // Build
      'build/',
      'dist/',
      'web-build/',
      'docs/.cache-loader/',
      'docs/.docusaurus/',
      'docs/build/',
      'docs/dist/',
      'docs/docs/components/',
      'docs/public/',
      'docs/static/',
      'example/coverage/',
      'example/dist/',

      // generated by bob
      'lib/',

      // Expo
      'example/.expo/',
      'example/android/',
      'example/ios/',
    ],
  },
  callstack,
  {
    plugins: {
      '@typescript-eslint': tseslint.plugin,
    },
    rules: {
      '@typescript-eslint/no-unused-vars': [
        'error',
        {
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^_',
          caughtErrors: 'none',
        },
      ],

      'import/no-extraneous-dependencies': [
        'error',
        {
          devDependencies: true,
          packageDir: ['.', './docs', './example'],
        },
      ],
      'import/order': [
        'error',
        {
          groups: [
            ['external', 'builtin'],
            'internal',
            ['sibling', 'parent'],
            'index',
          ],
          pathGroups: [
            {
              pattern: '@(react|react-native)',
              group: 'external',
              position: 'before',
            },
            {
              pattern: '@src/**',
              group: 'internal',
            },
          ],
          pathGroupsExcludedImportTypes: ['internal', 'react'],
          'newlines-between': 'always',
          alphabetize: {
            order: 'asc',
            caseInsensitive: true,
          },
        },
      ],

      '@react-native/platform-colors': 'error',

      'promise/no-callback-in-promise': 'error',
      'promise/no-nesting': 'error',
      'promise/no-promise-in-callback': 'error',
      'promise/no-return-in-finally': 'error',
      'promise/prefer-await-to-then': 'error',
      'promise/valid-params': 'error',

      'react-hooks/exhaustive-deps': 'error',

      'react/no-multi-comp': 'error',
      'react/react-in-jsx-scope': 'off',

      'react-native/no-color-literals': 'error',
      'react-native/no-inline-styles': 'error',
      'react-native/no-raw-text': 'off',
      'react-native/no-unused-styles': 'error',

      'react-native-a11y/has-valid-accessibility-descriptors': 'off',
    },
    settings: {
      'import/extensions': ['.js', '.mjs', '.ts', '.tsx'],
      'import/parsers': {
        '@typescript-eslint/parser': ['.ts', '.tsx'],
      },
      'import/resolver': {
        node: {
          extensions: ['.js', '.mjs', '.ts', '.tsx'],
        },
      },
    },
  },
  {
    files: ['**/*.test.{js,ts,tsx}', '**/__tests__/**/*.{js,ts,tsx}'],

    ...testingLibraryReact,

    settings: {
      ...testingLibraryReact.settings,

      'testing-library/custom-renders': ['render'],
      'testing-library/utils-module': 'test-utils',
    },
    rules: {
      ...testingLibraryReact.rules,

      'no-restricted-syntax': [
        'error',
        {
          selector:
            "MemberExpression[property.name='props']:not([object.type='ThisExpression'])",
          message:
            'Do not read TestInstance props directly. Prefer user-visible assertions.',
        },
        {
          selector:
            'CallExpression[callee.object.name="root"][callee.property.name=/^(find|findAll|findByType|findAllByType|findByProps|findAllByProps|query|queryAll)$/], CallExpression[callee.object.property.name="root"][callee.property.name=/^(find|findAll|findByType|findAllByType|findByProps|findAllByProps|query|queryAll)$/]',
          message:
            'Do not traverse react-test-renderer trees directly. Prefer user-visible queries.',
        },
        {
          selector:
            "CallExpression[callee.object.name='fireEvent'][callee.property.name=/^(press|longPress|changeText|scroll)$/]",
          message: 'Use userEvent for user interactions instead of fireEvent.',
        },
        {
          selector:
            "CallExpression[callee.name='fireEvent'][arguments.1.value=/^(press|longPress|onPress|onLongPress)$/][arguments.length=2]",
          message: 'Use userEvent for user interactions instead of fireEvent.',
        },
        {
          selector:
            "CallExpression[callee.name='fireEvent'][arguments.1.value=/^(changeText|onChangeText|scroll|onScroll)$/]",
          message: 'Use userEvent for user interactions instead of fireEvent.',
        },
      ],

      'jest/expect-expect': 'error',
      'jest/no-commented-out-tests': 'error',
      'jest/no-disabled-tests': 'error',
      'jest/prefer-importing-jest-globals': 'error',

      'react-native/no-inline-styles': 'off',

      'testing-library/no-await-sync-events': 'off',
      'testing-library/no-debugging-utils': 'error',
    },
  },
  {
    files: [
      'src/components/__tests__/Appbar/Appbar.test.tsx',
      'src/components/__tests__/Dialog.test.tsx',
      'src/components/__tests__/Searchbar.test.tsx',
    ],
    rules: {
      'testing-library/no-node-access': 'off',
    },
  },
  {
    files: ['src/components/__tests__/Tooltip.test.tsx'],
    rules: {
      'testing-library/no-node-access': 'off',
      'testing-library/prefer-screen-queries': 'off',
      'testing-library/render-result-naming-convention': 'off',
    },
  },
  {
    files: ['example/**/*.{js,ts,tsx}'],
    rules: {
      'react/prop-types': 'off',
    },
    settings: {
      'import/core-modules': ['react-native-paper'],
    },
  },
  {
    files: ['docs/**/*.{js,ts,tsx}'],
    settings: {
      'import/core-modules': [
        'react-native-paper',
        '@docusaurus/BrowserOnly',
        '@docusaurus/Link',
        '@docusaurus/plugin-content-docs/client',
        '@site/component-docs-plugin/useDocs',
        '@theme/Admonition',
        '@theme/CodeBlock',
        '@theme/TabItem',
        '@theme/Tabs',
      ],
    },
  },
  {
    files: ['eslint.config.mjs'],
    rules: {
      'import/no-unresolved': 'off',
    },
  }
);
