// flow-typed signature: fe99bfca51b5bf95718830566e6f70d0
// flow-typed version: <<STUB>>/color_v^2.0.1/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'color'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'color' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'color/index' {
  declare module.exports: $Exports<'color'>;
}
declare module 'color/index.js' {
  declare module.exports: $Exports<'color'>;
}
