// flow-typed signature: 3e17af33d9956a9eda6e17819fcabebd
// flow-typed version: <<STUB>>/eslint-plugin-react-native_v^3.2.0/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-react-native'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-react-native' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-plugin-react-native/lib/rules/no-color-literals' {
  declare module.exports: any;
}

declare module 'eslint-plugin-react-native/lib/rules/no-inline-styles' {
  declare module.exports: any;
}

declare module 'eslint-plugin-react-native/lib/rules/no-unused-styles' {
  declare module.exports: any;
}

declare module 'eslint-plugin-react-native/lib/rules/split-platform-components' {
  declare module.exports: any;
}

declare module 'eslint-plugin-react-native/lib/util/Components' {
  declare module.exports: any;
}

declare module 'eslint-plugin-react-native/lib/util/stylesheet' {
  declare module.exports: any;
}

declare module 'eslint-plugin-react-native/lib/util/variable' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-plugin-react-native/index' {
  declare module.exports: $Exports<'eslint-plugin-react-native'>;
}
declare module 'eslint-plugin-react-native/index.js' {
  declare module.exports: $Exports<'eslint-plugin-react-native'>;
}
declare module 'eslint-plugin-react-native/lib/rules/no-color-literals.js' {
  declare module.exports: $Exports<'eslint-plugin-react-native/lib/rules/no-color-literals'>;
}
declare module 'eslint-plugin-react-native/lib/rules/no-inline-styles.js' {
  declare module.exports: $Exports<'eslint-plugin-react-native/lib/rules/no-inline-styles'>;
}
declare module 'eslint-plugin-react-native/lib/rules/no-unused-styles.js' {
  declare module.exports: $Exports<'eslint-plugin-react-native/lib/rules/no-unused-styles'>;
}
declare module 'eslint-plugin-react-native/lib/rules/split-platform-components.js' {
  declare module.exports: $Exports<'eslint-plugin-react-native/lib/rules/split-platform-components'>;
}
declare module 'eslint-plugin-react-native/lib/util/Components.js' {
  declare module.exports: $Exports<'eslint-plugin-react-native/lib/util/Components'>;
}
declare module 'eslint-plugin-react-native/lib/util/stylesheet.js' {
  declare module.exports: $Exports<'eslint-plugin-react-native/lib/util/stylesheet'>;
}
declare module 'eslint-plugin-react-native/lib/util/variable.js' {
  declare module.exports: $Exports<'eslint-plugin-react-native/lib/util/variable'>;
}
