// flow-typed signature: c6d84edd5564399b8229cb625cffec89
// flow-typed version: <<STUB>>/eslint-config-callstack-io_v^1.1.1/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-callstack-io'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-callstack-io' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'eslint-config-callstack-io/index' {
  declare module.exports: $Exports<'eslint-config-callstack-io'>;
}
declare module 'eslint-config-callstack-io/index.js' {
  declare module.exports: $Exports<'eslint-config-callstack-io'>;
}
