import color from 'color';

import { state } from './state';
import type { ContrastLevel, ElevationColors, ThemeColors } from '../../types';
import { palette as defaultPalette } from '../ref/palette';

type Palette = typeof defaultPalette;
type PaletteKey = keyof Palette;

/** Roles that map 1:1 to a palette key. Excludes the computed fields. */
type MappedRoles = Omit<ThemeColors, 'stateLayerPressed' | 'elevation'>;

/** Role to palette step for each MD3 contrast level.
 *
 *  Raising contrast moves the accent and outline roles toward the extremes of
 *  their tonal palette. Surfaces and the `*Fixed` roles do not change, since
 *  MD3 keeps those stable across levels. */
const roleToTone: Record<
  'light' | 'dark',
  Record<ContrastLevel, Record<keyof MappedRoles, PaletteKey>>
> = {
  light: {
    standard: {
      primary: 'primary40',
      onPrimary: 'primary100',
      primaryContainer: 'primary90',
      onPrimaryContainer: 'primary10',
      secondary: 'secondary40',
      onSecondary: 'secondary100',
      secondaryContainer: 'secondary90',
      onSecondaryContainer: 'secondary10',
      tertiary: 'tertiary40',
      onTertiary: 'tertiary100',
      tertiaryContainer: 'tertiary90',
      onTertiaryContainer: 'tertiary10',
      error: 'error40',
      onError: 'error100',
      errorContainer: 'error90',
      onErrorContainer: 'error10',
      surface: 'neutral98',
      surfaceDim: 'neutral87',
      surfaceBright: 'neutral98',
      surfaceContainerLowest: 'neutral100',
      surfaceContainerLow: 'neutral96',
      surfaceContainer: 'neutral94',
      surfaceContainerHigh: 'neutral92',
      surfaceContainerHighest: 'neutral90',
      surfaceVariant: 'neutralVariant90',
      background: 'neutral98',
      onSurface: 'neutral10',
      onSurfaceVariant: 'neutralVariant30',
      onBackground: 'neutral10',
      outline: 'neutralVariant50',
      outlineVariant: 'neutralVariant80',
      inverseSurface: 'neutral20',
      inverseOnSurface: 'neutral95',
      inversePrimary: 'primary80',
      primaryFixed: 'primary90',
      primaryFixedDim: 'primary80',
      onPrimaryFixed: 'primary10',
      onPrimaryFixedVariant: 'primary30',
      secondaryFixed: 'secondary90',
      secondaryFixedDim: 'secondary80',
      onSecondaryFixed: 'secondary10',
      onSecondaryFixedVariant: 'secondary30',
      tertiaryFixed: 'tertiary90',
      tertiaryFixedDim: 'tertiary80',
      onTertiaryFixed: 'tertiary10',
      onTertiaryFixedVariant: 'tertiary30',
      shadow: 'neutral0',
      scrim: 'neutral0',
    },
    medium: {
      primary: 'primary30',
      onPrimary: 'primary100',
      primaryContainer: 'primary40',
      onPrimaryContainer: 'primary100',
      secondary: 'secondary30',
      onSecondary: 'secondary100',
      secondaryContainer: 'secondary40',
      onSecondaryContainer: 'secondary100',
      tertiary: 'tertiary30',
      onTertiary: 'tertiary100',
      tertiaryContainer: 'tertiary40',
      onTertiaryContainer: 'tertiary100',
      error: 'error30',
      onError: 'error100',
      errorContainer: 'error40',
      onErrorContainer: 'error100',
      surface: 'neutral98',
      surfaceDim: 'neutral87',
      surfaceBright: 'neutral98',
      surfaceContainerLowest: 'neutral100',
      surfaceContainerLow: 'neutral96',
      surfaceContainer: 'neutral94',
      surfaceContainerHigh: 'neutral92',
      surfaceContainerHighest: 'neutral90',
      surfaceVariant: 'neutralVariant90',
      background: 'neutral98',
      onSurface: 'neutral10',
      onSurfaceVariant: 'neutralVariant30',
      onBackground: 'neutral10',
      outline: 'neutralVariant40',
      outlineVariant: 'neutralVariant60',
      inverseSurface: 'neutral20',
      inverseOnSurface: 'neutral95',
      inversePrimary: 'primary90',
      primaryFixed: 'primary90',
      primaryFixedDim: 'primary80',
      onPrimaryFixed: 'primary10',
      onPrimaryFixedVariant: 'primary30',
      secondaryFixed: 'secondary90',
      secondaryFixedDim: 'secondary80',
      onSecondaryFixed: 'secondary10',
      onSecondaryFixedVariant: 'secondary30',
      tertiaryFixed: 'tertiary90',
      tertiaryFixedDim: 'tertiary80',
      onTertiaryFixed: 'tertiary10',
      onTertiaryFixedVariant: 'tertiary30',
      shadow: 'neutral0',
      scrim: 'neutral0',
    },
    high: {
      primary: 'primary20',
      onPrimary: 'primary100',
      primaryContainer: 'primary30',
      onPrimaryContainer: 'primary100',
      secondary: 'secondary20',
      onSecondary: 'secondary100',
      secondaryContainer: 'secondary30',
      onSecondaryContainer: 'secondary100',
      tertiary: 'tertiary20',
      onTertiary: 'tertiary100',
      tertiaryContainer: 'tertiary30',
      onTertiaryContainer: 'tertiary100',
      error: 'error20',
      onError: 'error100',
      errorContainer: 'error30',
      onErrorContainer: 'error100',
      surface: 'neutral98',
      surfaceDim: 'neutral87',
      surfaceBright: 'neutral98',
      surfaceContainerLowest: 'neutral100',
      surfaceContainerLow: 'neutral96',
      surfaceContainer: 'neutral94',
      surfaceContainerHigh: 'neutral92',
      surfaceContainerHighest: 'neutral90',
      surfaceVariant: 'neutralVariant90',
      background: 'neutral98',
      onSurface: 'neutral0',
      onSurfaceVariant: 'neutralVariant20',
      onBackground: 'neutral0',
      outline: 'neutralVariant20',
      outlineVariant: 'neutralVariant40',
      inverseSurface: 'neutral20',
      inverseOnSurface: 'neutral95',
      inversePrimary: 'primary95',
      primaryFixed: 'primary90',
      primaryFixedDim: 'primary80',
      onPrimaryFixed: 'primary10',
      onPrimaryFixedVariant: 'primary20',
      secondaryFixed: 'secondary90',
      secondaryFixedDim: 'secondary80',
      onSecondaryFixed: 'secondary10',
      onSecondaryFixedVariant: 'secondary20',
      tertiaryFixed: 'tertiary90',
      tertiaryFixedDim: 'tertiary80',
      onTertiaryFixed: 'tertiary10',
      onTertiaryFixedVariant: 'tertiary20',
      shadow: 'neutral0',
      scrim: 'neutral0',
    },
  },
  dark: {
    standard: {
      primary: 'primary80',
      onPrimary: 'primary20',
      primaryContainer: 'primary30',
      onPrimaryContainer: 'primary90',
      secondary: 'secondary80',
      onSecondary: 'secondary20',
      secondaryContainer: 'secondary30',
      onSecondaryContainer: 'secondary90',
      tertiary: 'tertiary80',
      onTertiary: 'tertiary20',
      tertiaryContainer: 'tertiary30',
      onTertiaryContainer: 'tertiary90',
      error: 'error80',
      onError: 'error20',
      errorContainer: 'error30',
      onErrorContainer: 'error80',
      surface: 'neutral6',
      surfaceDim: 'neutral6',
      surfaceBright: 'neutral24',
      surfaceContainerLowest: 'neutral4',
      surfaceContainerLow: 'neutral10',
      surfaceContainer: 'neutral12',
      surfaceContainerHigh: 'neutral17',
      surfaceContainerHighest: 'neutral22',
      surfaceVariant: 'neutralVariant30',
      background: 'neutral6',
      onSurface: 'neutral90',
      onSurfaceVariant: 'neutralVariant80',
      onBackground: 'neutral90',
      outline: 'neutralVariant60',
      outlineVariant: 'neutralVariant30',
      inverseSurface: 'neutral90',
      inverseOnSurface: 'neutral20',
      inversePrimary: 'primary40',
      primaryFixed: 'primary90',
      primaryFixedDim: 'primary80',
      onPrimaryFixed: 'primary10',
      onPrimaryFixedVariant: 'primary30',
      secondaryFixed: 'secondary90',
      secondaryFixedDim: 'secondary80',
      onSecondaryFixed: 'secondary10',
      onSecondaryFixedVariant: 'secondary30',
      tertiaryFixed: 'tertiary90',
      tertiaryFixedDim: 'tertiary80',
      onTertiaryFixed: 'tertiary10',
      onTertiaryFixedVariant: 'tertiary30',
      shadow: 'neutral0',
      scrim: 'neutral0',
    },
    medium: {
      primary: 'primary90',
      onPrimary: 'primary10',
      primaryContainer: 'primary70',
      onPrimaryContainer: 'primary0',
      secondary: 'secondary90',
      onSecondary: 'secondary10',
      secondaryContainer: 'secondary70',
      onSecondaryContainer: 'secondary0',
      tertiary: 'tertiary90',
      onTertiary: 'tertiary10',
      tertiaryContainer: 'tertiary70',
      onTertiaryContainer: 'tertiary0',
      error: 'error90',
      onError: 'error10',
      errorContainer: 'error70',
      onErrorContainer: 'error0',
      surface: 'neutral6',
      surfaceDim: 'neutral6',
      surfaceBright: 'neutral24',
      surfaceContainerLowest: 'neutral4',
      surfaceContainerLow: 'neutral10',
      surfaceContainer: 'neutral12',
      surfaceContainerHigh: 'neutral17',
      surfaceContainerHighest: 'neutral22',
      surfaceVariant: 'neutralVariant30',
      background: 'neutral6',
      onSurface: 'neutral100',
      onSurfaceVariant: 'neutralVariant90',
      onBackground: 'neutral100',
      outline: 'neutralVariant70',
      outlineVariant: 'neutralVariant50',
      inverseSurface: 'neutral90',
      inverseOnSurface: 'neutral20',
      inversePrimary: 'primary30',
      primaryFixed: 'primary90',
      primaryFixedDim: 'primary80',
      onPrimaryFixed: 'primary10',
      onPrimaryFixedVariant: 'primary30',
      secondaryFixed: 'secondary90',
      secondaryFixedDim: 'secondary80',
      onSecondaryFixed: 'secondary10',
      onSecondaryFixedVariant: 'secondary30',
      tertiaryFixed: 'tertiary90',
      tertiaryFixedDim: 'tertiary80',
      onTertiaryFixed: 'tertiary10',
      onTertiaryFixedVariant: 'tertiary30',
      shadow: 'neutral0',
      scrim: 'neutral0',
    },
    high: {
      primary: 'primary95',
      onPrimary: 'primary0',
      primaryContainer: 'primary80',
      onPrimaryContainer: 'primary0',
      secondary: 'secondary95',
      onSecondary: 'secondary0',
      secondaryContainer: 'secondary80',
      onSecondaryContainer: 'secondary0',
      tertiary: 'tertiary95',
      onTertiary: 'tertiary0',
      tertiaryContainer: 'tertiary80',
      onTertiaryContainer: 'tertiary0',
      error: 'error95',
      onError: 'error0',
      errorContainer: 'error80',
      onErrorContainer: 'error0',
      surface: 'neutral6',
      surfaceDim: 'neutral6',
      surfaceBright: 'neutral24',
      surfaceContainerLowest: 'neutral4',
      surfaceContainerLow: 'neutral10',
      surfaceContainer: 'neutral12',
      surfaceContainerHigh: 'neutral17',
      surfaceContainerHighest: 'neutral22',
      surfaceVariant: 'neutralVariant30',
      background: 'neutral6',
      onSurface: 'neutral100',
      onSurfaceVariant: 'neutralVariant95',
      onBackground: 'neutral100',
      outline: 'neutralVariant80',
      outlineVariant: 'neutralVariant60',
      inverseSurface: 'neutral90',
      inverseOnSurface: 'neutral20',
      inversePrimary: 'primary20',
      primaryFixed: 'primary90',
      primaryFixedDim: 'primary80',
      onPrimaryFixed: 'primary10',
      onPrimaryFixedVariant: 'primary20',
      secondaryFixed: 'secondary90',
      secondaryFixedDim: 'secondary80',
      onSecondaryFixed: 'secondary10',
      onSecondaryFixedVariant: 'secondary20',
      tertiaryFixed: 'tertiary90',
      tertiaryFixedDim: 'tertiary80',
      onTertiaryFixed: 'tertiary10',
      onTertiaryFixedVariant: 'tertiary20',
      shadow: 'neutral0',
      scrim: 'neutral0',
    },
  },
};

const elevationToTone: Record<
  'light' | 'dark',
  Record<Exclude<keyof ElevationColors, 'level0'>, PaletteKey>
> = {
  light: {
    level1: 'neutral96',
    level2: 'neutral94',
    level3: 'neutral92',
    level4: 'neutral92',
    level5: 'neutral90',
  },
  dark: {
    level1: 'neutral10',
    level2: 'neutral12',
    level3: 'neutral17',
    level4: 'neutral17',
    level5: 'neutral22',
  },
};

/** Works out the press state layer up front, because changing alpha at
 *  runtime breaks PlatformColor on Android.
 *  @see ThemeColors.stateLayerPressed */
const withPressedOpacity = (onSurface: string) =>
  color(onSurface).alpha(state.opacity.pressed).rgb().string();

/** Builds the color scheme for a mode and contrast level. */
export function buildScheme(
  palette: Palette,
  opts: { mode: 'light' | 'dark'; contrast?: ContrastLevel }
): ThemeColors {
  const contrast = opts.contrast ?? 'standard';
  const tones = roleToTone[opts.mode][contrast];
  const elevTones = elevationToTone[opts.mode];

  // eslint-disable-next-line @typescript-eslint/no-unsafe-type-assertion
  const mapped = Object.fromEntries(
    Object.entries(tones).map(([role, tone]) => [role, palette[tone]])
  ) as MappedRoles;

  return {
    ...mapped,
    stateLayerPressed: withPressedOpacity(palette[tones.onSurface]),
    elevation: {
      level0: 'transparent',
      level1: palette[elevTones.level1],
      level2: palette[elevTones.level2],
      level3: palette[elevTones.level3],
      level4: palette[elevTones.level4],
      level5: palette[elevTones.level5],
    },
  };
}
