/**
 * Generates the MD3 medium and high contrast schemes into
 * `src/theme/tokens/sys/contrastSchemes.ts`.
 *
 * MD3 does not pick a different palette step for medium and high contrast.
 * For each role it looks for the tone that hits a target contrast ratio
 * against that role's background. The tones it finds are usually not whole numbers.
 * For example `primary` at light/high lands on tone 13.3, so it cannot be
 * written as a key of `ref/palette.ts`.
 *
 * Run with `yarn generate-contrast-tokens`.
 */
import {
  Hct,
  MaterialDynamicColors,
  SchemeTonalSpot,
  argbFromHex,
  blueFromArgb,
  greenFromArgb,
  redFromArgb,
} from '@material/material-color-utilities';
import { writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import type { ElevationColors, ThemeColors } from '../src/theme/types';

type Role = Exclude<keyof ThemeColors, 'stateLayerPressed' | 'elevation'>;

type ElevationKey = Exclude<keyof ElevationColors, 'level0'>;

const SEED = '#6750A4';

const MODES = [
  ['light', false],
  ['dark', true],
] as const;

const CONTRASTS = [
  ['medium', 0.5],
  ['high', 1.0],
] as const;

// The roles to generate, in the order they are written to the output file.
const ROLES = [
  'primary',
  'primaryContainer',
  'secondary',
  'secondaryContainer',
  'tertiary',
  'tertiaryContainer',
  'surface',
  'surfaceDim',
  'surfaceBright',
  'surfaceContainerLowest',
  'surfaceContainerLow',
  'surfaceContainer',
  'surfaceContainerHigh',
  'surfaceContainerHighest',
  'surfaceVariant',
  'background',
  'error',
  'errorContainer',
  'onPrimary',
  'onPrimaryContainer',
  'onSecondary',
  'onSecondaryContainer',
  'onTertiary',
  'onTertiaryContainer',
  'onSurface',
  'onSurfaceVariant',
  'onError',
  'onErrorContainer',
  'onBackground',
  'outline',
  'outlineVariant',
  'inverseSurface',
  'inverseOnSurface',
  'inversePrimary',
  'primaryFixed',
  'primaryFixedDim',
  'onPrimaryFixed',
  'onPrimaryFixedVariant',
  'secondaryFixed',
  'secondaryFixedDim',
  'onSecondaryFixed',
  'onSecondaryFixedVariant',
  'tertiaryFixed',
  'tertiaryFixedDim',
  'onTertiaryFixed',
  'onTertiaryFixedVariant',
  'shadow',
  'scrim',
] as const satisfies readonly Role[];

// Fails to compile if a role in `ThemeColors` is missing from `ROLES`.
type MissingRoles = Exclude<Role, (typeof ROLES)[number]>;

type AssertNoMissingRoles<T extends never> = T;

export type _RolesAreComplete = AssertNoMissingRoles<MissingRoles>;

/**
 * Tonal elevation surfaces. MD3 maps these onto the surface container roles.
 * `level0` is always transparent, so it is not generated.
 */
const ELEVATION_ROLES: Record<ElevationKey, Role> = {
  level1: 'surfaceContainerLow',
  level2: 'surfaceContainer',
  level3: 'surfaceContainerHigh',
  level4: 'surfaceContainerHigh',
  level5: 'surfaceContainerHighest',
};

/** Matches the `rgba(r, g, b, 1)` format used throughout the theme tokens. */
const toRgbaString = (argb: number) =>
  `rgba(${redFromArgb(argb)}, ${greenFromArgb(argb)}, ${blueFromArgb(argb)}, 1)`;

const lookupRole = (role: string): unknown =>
  Object.entries(MaterialDynamicColors).find(([key]) => key === role)?.[1];

const resolveRole = (scheme: SchemeTonalSpot, role: string) => {
  const dynamicColor = lookupRole(role);

  if (
    dynamicColor == null ||
    typeof dynamicColor !== 'object' ||
    !('getArgb' in dynamicColor) ||
    typeof dynamicColor.getArgb !== 'function'
  ) {
    throw new Error(
      `@material/material-color-utilities does not expose the "${role}" role. ` +
        `Check the pinned version, role coverage differs between releases.`
    );
  }

  return toRgbaString(dynamicColor.getArgb(scheme));
};

const seed = Hct.fromInt(argbFromHex(SEED));

const schemes = MODES.map(([mode, isDark]) => {
  const contrasts = CONTRASTS.map(([contrast, level]) => {
    const scheme = new SchemeTonalSpot(seed, isDark, level);

    const roles = ROLES.map(
      (role) => `        ${role}: '${resolveRole(scheme, role)}',`
    ).join('\n');

    const elevation = Object.entries(ELEVATION_ROLES)
      .map(([key, role]) => `        ${key}: '${resolveRole(scheme, role)}',`)
      .join('\n');

    return [
      `    ${contrast}: {`,
      `      roles: {`,
      roles,
      `      },`,
      `      elevation: {`,
      elevation,
      `      },`,
      `    },`,
    ].join('\n');
  }).join('\n');

  return [`  ${mode}: {`, contrasts, `  },`].join('\n');
}).join('\n');

const output = `/**
 * GENERATED by scripts/generate-contrast-tokens.ts, do not edit by hand.
 * Run \`yarn generate-contrast-tokens\` to regenerate.
 *
 * MD3 medium and high contrast schemes, seeded from ${SEED}.
 *
 */
import type { ContrastLevel, ElevationColors, ThemeColors } from '../../types';

type GeneratedContrast = Exclude<ContrastLevel, 'standard'>;

type GeneratedScheme = {
  roles: Record<
    Exclude<keyof ThemeColors, 'stateLayerPressed' | 'elevation'>,
    string
  >;
  elevation: Record<Exclude<keyof ElevationColors, 'level0'>, string>;
};

export const contrastSchemes: Record<
  'light' | 'dark',
  Record<GeneratedContrast, GeneratedScheme>
> = {
${schemes}
} as const;
`;

const scriptDir = dirname(fileURLToPath(import.meta.url));
const outputPath = resolve(
  scriptDir,
  '..',
  'src/theme/tokens/sys/contrastSchemes.ts'
);

writeFileSync(outputPath, output);

console.log(
  `Generated ${ROLES.length} roles x ${MODES.length} modes x ${CONTRASTS.length} contrast levels -> ${outputPath}`
);
