#!/usr/bin/env node
/**
 * Regenerates example/visual/evidence/summary.md from the raw agent-device JSON
 * kept under example/visual/evidence/.
 *
 *   node example/visual/evidence/summarize.mjs [evidence-dir]
 *
 * Every *.json that reports a diff is picked up: an agent-device `diff` payload
 * (`data.differentPixels`) or a run.mjs summary.json (one row per entry in
 * `results`). Files are grouped into one table per directory, in walk order.
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const COLUMNS = [
  'file',
  'total px',
  'changed px',
  'mismatch %',
  'regions',
  'match',
];

/** Every *.json under `dir`, depth-first, directories and files sorted. */
function jsonFiles(dir) {
  const found = [];
  for (const entry of fs
    .readdirSync(dir, { withFileTypes: true })
    .sort((a, b) => a.name.localeCompare(b.name))) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) found.push(...jsonFiles(full));
    else if (entry.name.endsWith('.json')) found.push(full);
  }
  return found;
}

/** The diff rows a single JSON file contributes, or [] if it reports no diff. */
function rowsOf(file) {
  let json;
  try {
    json = JSON.parse(fs.readFileSync(file, 'utf8'));
  } catch {
    return [];
  }

  const name = path.basename(file);

  if (json?.data?.differentPixels != null) {
    const d = json.data;
    return [
      {
        file: name,
        total: d.totalPixels,
        changed: d.differentPixels,
        mismatch: d.mismatchPercentage,
        regions: d.regions?.length ?? 0,
        match: d.match,
      },
    ];
  }

  // run.mjs summary.json: the diff numbers live one level down, per story.
  if (Array.isArray(json?.results)) {
    return json.results
      .filter((r) => r.changedPixels != null)
      .map((r) => ({
        file: `${name} (${r.story})`,
        total: r.totalPixels,
        changed: r.changedPixels,
        mismatch: r.mismatchPercentage,
        regions: r.regions?.length ?? 0,
        match: r.pass,
      }));
  }

  return [];
}

function renderTable(rows) {
  const cells = rows.map((r) => [
    r.file,
    String(r.total ?? ''),
    String(r.changed ?? ''),
    String(r.mismatch ?? ''),
    String(r.regions ?? ''),
    r.match ? 'yes' : 'no',
  ]);
  const widths = COLUMNS.map((header, i) =>
    Math.max(header.length, ...cells.map((c) => c[i].length))
  );
  const line = (values) =>
    `| ${values.map((v, i) => v.padEnd(widths[i])).join(' | ')} |`;

  return [
    line(COLUMNS),
    `| ${widths.map((w) => '-'.repeat(w)).join(' | ')} |`,
    ...cells.map(line),
  ].join('\n');
}

function main() {
  const root = path.resolve(
    process.argv[2] || path.dirname(fileURLToPath(import.meta.url))
  );

  const sections = new Map();
  for (const file of jsonFiles(root)) {
    const rows = rowsOf(file);
    if (rows.length === 0) continue;
    const section = `${path.relative(root, path.dirname(file)) || '.'}/`;
    sections.set(section, [...(sections.get(section) || []), ...rows]);
  }

  const out = [
    '# Evidence summary',
    '',
    'generated by evidence/summarize.mjs — do not edit by hand',
    '',
    ...[...sections].flatMap(([section, rows]) => [
      `## ${section}`,
      '',
      renderTable(rows),
      '',
    ]),
  ].join('\n');

  const target = path.join(root, 'summary.md');
  fs.writeFileSync(target, out);
  const total = [...sections.values()].reduce((n, r) => n + r.length, 0);
  console.log(`${target}: ${total} rows in ${sections.size} sections`);
}

main();
