name: Expo EAS Updates
on:
  push:
    branches:
      - main
jobs:
  publish:
    if: ${{ (contains(github.event.pull_request.labels.*.name, 'example app')) }}
    name: Install and publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup
        uses: ./.github/actions/setup

      - name: Setup Expo
        uses: expo/expo-github-action@c7b66a9c327a43a8fa7c0158e7f30d6040d2481e # v8.2.1
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Publish Expo app update
        working-directory: ./example
        run: eas update --auto
